igclone/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('media.urls', 'media'), namespace='media')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

media/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from . import views
from media.models import fs

urlpatterns = [
    url(r'^$', views.UserFeed, name='feed'),
    url(r'^profile/(?P<username>\w+)/$', views.ProfilePage, name="profile"),
    url(r'^post/', include([
        url(r'^(?P<pk>\w+)/$', views.PostPage, name="post"),
        url(r'^$', views.MakePost.as_view(), name="make_post"),
        ])),
    url(r'^comment/(?P<pk>\w+)/$', views.MakeComment, name="comment"),
]

users/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^logout/$', views.LogoutView, name="logout"),    
    url(r'^search/$', views.SearchProfiles, name="search"),
    url(r'^follow/(?P<pk>\w+)/$', views.FollowView, name="follow"),
    url(r'^unfollow/(?P<pk>\w+)/$', views.UnfollowView, name="unfollow")
]

media/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location='media/posts/')

class Post(models.Model):
    posted_by = models.ForeignKey(
        'users.Profile',
        related_name="posts",
        on_delete=models.CASCADE
    )
    photo = models.ImageField(storage=fs)
    caption = models.CharField(max_length=500, null=True, blank=True)
    post_date = models.DateTimeField(auto_now_add=True, db_index=True)

class Comment(models.Model):
    posted_on = models.ForeignKey(
        'media.Post',
        related_name="comments",
        on_delete=models.CASCADE
    )
    posted_by = models.ForeignKey(
        'users.Profile',
        related_name="commented",
        on_delete=models.CASCADE
    )
    comment = models.CharField(max_length=500)
    post_date = models.DateTimeField(auto_now_add=True, db_index=True)

media/views.py
import os
from functools import reduce
from django.db import transaction
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from rest_framework.response import Response
from rest_framework.views import  APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string

from users.models import Profile, Follower
from media.models import Post, Comment, fs as PhotoStorage

@login_required
def UserFeed(request):
    """
    view to return user feed
    """
    template = loader.get_template('media/feed.html')
    user = request.user
    following = user.get_following()
    #combining the posts of all users that are followed by this profile
    posts = reduce(lambda x,y: x+y,[ list(f.posts.all()) for f in following ], [])
    #sorting in order of most recent
    posts = sorted(posts, key=lambda p: p.post_date, reverse=True)
    context = {
        'post_set': posts
    }
    return HttpResponse(template.render(context, request))

@login_required
def ProfilePage(request, username):
    """
    Profile page that displays all the user's photos
    """
    user = request.user
    profile = Profile.objects.get(username=username)
    template = loader.get_template('media/profile.html')
    posts = profile.get_posts()
    print(user == profile)
    print(user.is_following_user(profile.pk))
    context = {
        'is_you' : user == profile,
        'profile': profile,
        'post_set': posts,
        'following': user.is_following_user(profile.pk)
    }
    return HttpResponse(template.render(context, request))

@login_required
def PostPage(request, pk):
    """
    Post page that displays all the comments
    """
    post = Post.objects.get(pk=pk)
    template = loader.get_template('media/post.html')
    comments = post.comments.order_by('-post_date').all()
    context = {
        'post': post,
        'comment_set': comments
    }
    return HttpResponse(template.render(context, request))


class MakePost(APIView):
    """
    View function for making posts.

    Returns Post upon success
    """
    #[Needs Validator]
    permissions_classes = (IsAuthenticated,)
    
    def get(self, request):
        user = request.user
        template = loader.get_template('media/make_post.html')
        
        return HttpResponse(template.render({}, request))

    @transaction.atomic
    def post(self, request):
        caption = request.data.get('caption')
        photo = request.FILES['photo']
        print(photo.name)
        post = Post.objects.create(
            posted_by=request.user,
            photo=photo,
            caption=caption
        )

        name = "%d_%d_" % (request.user.pk, post.pk)
        name = name + get_random_string(length=32) + "." + post.photo.name.split('.')[-1]
        old_path = post.photo.path
        post.photo.name = name
        path = PhotoStorage.path(name)
        os.rename(old_path, path)
        post.save()

        return HttpResponseRedirect(reverse('media:post', kwargs={ 'pk': post.pk}))

@api_view(['POST',])
@permission_classes([IsAuthenticated,])
def MakeComment(request, pk):
    """
    """
    #[Needs Validator]

    comment = request.data.get('comment')
    if not comment:
        raise ValueError('Caption is required')
    else:
        comment = Comment.objects.create(
            posted_by=request.user,
            posted_on_id=pk,
            comment=comment
        )

        return HttpResponseRedirect(reverse('media:post', kwargs={'pk': comment.posted_on.pk}))

media/templates/media/feed.html
<div style="text-align: center;">
	<div style="text-align: right;">
		<a href="{% url 'users:logout' %}">logout</a>
	</div>
<a href="{% url 'media:make_post' %}">New Post</a>
<form action="{% url 'users:search' %}" method="get">
	<input type="text" name="search">
	<input type="submit" value="Search For Users">
</form>
{% for post in post_set %}
<div style="display: inline-block;overflow-y:auto;">
  <img src="{{ post.photo.url}}" style="height:300px;width:300px;object-fit:scale-down;"></img>
  <div style="text-align: left;">
    <h5><a href="{% url 'media:profile' post.posted_by.username %}">
      {{ post.posted_by.username }}
    </a> {{post.caption}}</h5>
    <h5>Posted on {{post.post_date}}</h5>
    <a href="{% url 'media:post' post.pk %}">See Comments...</a>
  </div>
<div>
{% endfor %}
</div>

media/templates/media/make_post.html
<div style="text-align:center;">
	<div style="display:inline-block;width:300px;text-align:left;">	
		<h3>Post an Image</h3>
		<form action="{% url 'media:make_post' %}"` method="post" enctype="multipart/form-data">
		{% csrf_token %}
			<h3>Image</h3>
			<input type="file" name="photo" accept="image/*">
			<h3>Caption</h3>
			<input type="text" name="caption">
			<input type="submit" value="Submit">
		</form>
	</div>
</div>

media/templates/media/post.html
<div style="text-align: center;">
  <div style="text-align: right;">
  	<a href="{% url 'users:logout' %}">logout</a>
  </div>
  <a href="{% url 'media:make_post' %}">New Post</a>
  <form action="{% url 'users:search' %}">
	<input type="text" name="search">
	<input type="submit" value="Search for Users">
  </form>
  <div style="display:inline-block; text-align: left;">
    <img src="{{ post.photo.url }}" style="height:300px;width:300px;object-fit:scale-down;"></img>
    <h5><a href="{% url 'media:profile' post.posted_by.username %}">{{post.posted_by.username}}</a> {{post.caption}}</h5>
    <h5>Posted on {{post.post_date}}</h5>

    <h3>Comments</h3>
    <form action="{% url 'media:comment' post.pk %}" method="post">
    {% csrf_token %}
      <input type="text" name="comment" style="width:300px;">
      <div style="text-align:right;">
      	<input type="submit" value="Comment">
      </div>
    </form>
    {% for comment in comment_set %}
    <div><a href="{% url 'media:profile' comment.posted_by.username %}">{{ comment.posted_by.username }}</a> {{ comment.comment }}</div>
      <div>Posted on {{ comment.post_date}}</div>
    {% endfor %}
  </div>
</div>

media/templates/media/profile.html
{% load mathfilters %}

<div style="text-align: center;">
  <div style="text-align:right;">
  	<a href="{% url 'users:logout' %}">logout</a>
  </div>
  <a href="{% url 'media:make_post' %}">New Post</a>
  <form action="{% url 'users:search' %}" method="get">
	<input type="text" name="search">
	<input type="submit" value="Search for Users">
  </form>
  <div style="display:inline-block; text-align: left; width: 1000px;">
    <h2>{{ profile.username }}</h2>
      <div>
	{% if is_you is False %}
	   {% if following is True %}
	   <form action={% url 'users:unfollow' profile.pk %} method="post">
		{% csrf_token %}
		<input type="submit" value="unfollow">
	   </form>
	   {% else %}
	   <form action={% url 'users:follow' profile.pk %} method="post"> 
		{% csrf_token %}
	        <input type="submit" value="follow">
	   </form>
	   {% endif %}
	{% endif %}
      <div>
        {% if profile.bio %}
          {{ profile.bio }}
        {% endif %}
      </div>
      <div>
        {{ profile.followers.count }} followers {{ profile.following.count }} following
      </div>
      <div>
      {% for post in post_set %}
        <a href="{% url 'media:post' post.pk %}"><img src="{{ post.photo.url }}" style="height:300px;width:300px;object-fit:scale-down;"></img></a>
      {% if forloop.counter|mod:3 == 0 %}
      </div>
      <div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
</div>